{
    'name': 'Ostrich',
    'version': '1.0',
    'category': 'Health and Fitness',
    'summary': 'The perfect module for every ostrich',
    'website': '',
    'depends': ['st_bird', 'st_herbivorous'],
    'data': [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'price': 25.00,
    'currency': 'EUR',
    'license': 'OEEL-1',
}
