{
    'name': 'Crow',
    'version': '1.0',
    'category': 'Retail',
    'summary': 'The perfect module for every crow',
    'website': '',
    'depends': ['st_bird', 'st_herbivorous'],
    'data': [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'price': 50.00,
    'currency': 'EUR',
    'license': 'OPL-1',
}
