{
    'name': 'Duck',
    'version': '1.0',
    'category': 'Hospitality',
    'summary': 'The perfect module for every duck',
    'website': '',
    'depends': ['st_bird', 'st_omnivorous'],
    'data': [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'price': 10.00,
    'currency': 'EUR',
    'license': 'OPL-1',
}
