{
    'name': 'Insect',
    'version': '1.0',
    'category': 'Accounting',
    'summary': 'The base folder for the insects',
    'website': '',
    'depends': [],
    'data': [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'price': 0.00,
    'currency': 'EUR',
}
