{
    'name': 'Fish',
    'version': '1.0',
    'category': 'Accounting',
    'summary': 'The base folder for the fishes',
    'description': "A dummy module that is used as a basis for every fish",
    'website': '',
    'depends': [],
    'data': [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'price': 30.00,
    'currency': 'EUR',
}
